# Generated by Django 5.2 on 2026-05-25 06:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_source',
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('FUEL', 'Fuel & Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('TRAVEL', 'Business Travel')], max_length=20)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(max_length=20)),
                ('normalized_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor_source', models.CharField(max_length=100)),
                ('kgco2e', models.DecimalField(decimal_places=4, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_of_truth', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emission_record',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('senior_analyst', 'Senior Analyst'), ('admin', 'Admin')], default='analyst', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='emissions.tenant')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityDetail',
            fields=[
                ('emission_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='electricity_detail', serialize=False, to='emissions.emissionrecord')),
                ('meter_no', models.CharField(max_length=50)),
                ('account_no', models.CharField(blank=True, max_length=50)),
                ('tariff_category', models.CharField(blank=True, max_length=50)),
                ('billing_from', models.DateField()),
                ('billing_to', models.DateField()),
                ('gross_kwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('solar_offset_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('net_kwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('grid_factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('grid_factor_source', models.CharField(default='CEA_2023', max_length=100)),
                ('is_prorated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'electricity_detail',
            },
        ),
        migrations.CreateModel(
            name='FuelDetail',
            fields=[
                ('emission_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fuel_detail', serialize=False, to='emissions.emissionrecord')),
                ('material_no', models.CharField(blank=True, max_length=50)),
                ('material_group', models.CharField(blank=True, max_length=20)),
                ('fuel_type', models.CharField(max_length=50)),
                ('plant_code', models.CharField(max_length=10)),
                ('vendor_no', models.CharField(blank=True, max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=20)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=10)),
                ('original_unit', models.CharField(max_length=10)),
                ('original_qty', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'fuel_detail',
            },
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('emission_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='travel_detail', serialize=False, to='emissions.emissionrecord')),
                ('report_id', models.CharField(blank=True, max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('segment_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND', 'Ground Transport')], max_length=10)),
                ('origin_iata', models.CharField(blank=True, max_length=3)),
                ('dest_iata', models.CharField(blank=True, max_length=3)),
                ('carrier', models.CharField(blank=True, max_length=10)),
                ('cabin_class', models.CharField(blank=True, choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('class_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('hotel_city', models.CharField(blank=True, max_length=100)),
                ('hotel_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ground_type', models.CharField(blank=True, max_length=50)),
                ('has_receipt', models.BooleanField(default=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'db_table': 'travel_detail',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('EDIT', 'Edited'), ('APPROVE', 'Approved'), ('FLAG', 'Flagged'), ('LOCK', 'Locked'), ('REVERT', 'Reverted')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.facility'),
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='emissions.facility')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='emissions.datasource')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.tenant')),
            ],
            options={
                'db_table': 'ingestion_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.ingestionbatch'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'Parsed OK'), ('WARNING', 'Parsed with Warnings'), ('FAILED', 'Parse Failed')], default='OK', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.ingestionbatch')),
            ],
            options={
                'db_table': 'raw_record',
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='emissions.rawrecord'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='emissions.tenant'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.tenant'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'plant_code')},
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emission_re_tenant__d122f8_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emission_re_tenant__86cc45_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='emission_re_tenant__dfaafd_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['facility'], name='emission_re_facilit_e22711_idx'),
        ),
    ]
